IRAS/IRAS/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include(('app.urls','app'),namespace='app')),
]

IRAS/app/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path(r'',views.index,name='index'),
    # 当url匹配到参数1时，调用views模块的index函数进行request处理
    path(r'single-result-fig',views.sf,name='sf'),
    path(r'single-result-res',views.sr,name='sr'),
    path(r'single-result-vis',views.sv,name='sv'),
    path(r'single-result/<int:itv_id>',views.singleres,name='singleres'),
    path(r'single',views.single,name='single'),
    path(r'multi-result',views.multires,name='multires'),
    path(r'multi-match',views.multimatch,name='multimatch'),
    path(r'multi-vis',views.multivis,name='multivis'),
    path(r'multi-upload-resume',views.multiupres,name='multiupres'),
    path(r'multi-upload-position',views.multiuppos,name='multiuppos'),
    path(r'multiply',views.multiply,name='multiply'),
    path(r'single-upload',views.singleupload,name='singleupload'),
    path(r'multiply-upload',views.multiupload,name='multiupload'),
    path(r'about/',views.about,name='about'),
]

IRAS/app/templates/app/about.html
<!DOCTYPE html>
<!-- saved from url=(0057)file:///D:/tencent%20files/1581928363/filerecv/about.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <title>About Us</title>
  <!-- <link rel="stylesheet" type="text/css" href="style.css"> -->
  <style>
    body {
  font-family: Arial, sans-serif;
  margin: 0;
  padding: 20px;
  background-image: url("../../static/app/images/backg.jpg");
}

header {
  text-align: center;
  margin-bottom: 40px;
}

h1 {
  font-size: 32px;
}

section {
  margin-bottom: 40px;
}

h2 {
  font-size: 24px;
}

p {
  font-size: 18px;
  margin: 10px 0;
}

footer {
  text-align: center;
  padding-top: 20px;
  border-top: 1px solid #ccc;
}

footer p {
  font-size: 14px;
  color: #666;
}
  </style>
</head>
<body>
  <header>
    <h1>关于我们</h1>
  </header>
  <main>
    <section>
      <h2>联系方式</h2>
      <p>Email: nileonx@gmail.com</p>
      <p>QQ: 2661531273</p>
    </section>
    <section>
      <h2>地址</h2>
      <p>陕西省西安市碑林区太乙路咸宁西路28号西安交通大学兴庆校区</p>
      <!-- <p>City, State 12345</p> -->
    </section>
  </main>
  <footer>
    <!-- <p>&copy; 2023 . All rights reserved.</p> -->
  </footer>

</body></html>

IRAS/app/templates/app/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {
      margin: 0;
      font-family: Arial, sans-serif;
      background-image: url("../../static/app/images/backg.jpg");
    }

    .sidebar {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px;
      background-color: #0d6efd;
      color: #fff;
    }

    .sidebar h1 {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
    }

    .nav-item, .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #0d6efd;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .nav-item.selected, .nav-item:hover {
      background-color: #0355cf;
      color: #fff;
    }

    .main-container {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: calc(100vh - 80px);
    }

    .content-container {
      display: flex;
      justify-content: center;
      margin-top: 50px;
    }

    .analysis-section {
      display: flex;
      flex: 1;
      flex-direction: column;
      align-items: center;
      margin: 0 20px;
    }

    .image-container {
      width: 200px;
      height: 200px;
      background-color: #f2f2f2;
      border-radius: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 20px; /* Add margin-bottom to create space between image and button */
    }

    .analyze-button  {
      padding: 8px 16px;
      background-color: #fff;
      color: #0d6efd;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-top: 10px; /* Add margin-top to separate the buttons from the image */
      cursor: pointer;
      transition: background-color 0.3s ease;
    }
    .analyze-button.selected, .analyze-button:hover {
      background-color: #0d6efd;
      color: #fff;
    }
  </style>
  <script>
    function loadPage( menuItem) {
      pageURL=menuItem.getAttribute("data-url");
      if (menuItem.classList.contains("nav-item")) {
        window.location.href = pageURL;
      } else {
        var subMenuItems = document.getElementsByClassName("sub-menu-item");
        for (var i = 0; i < subMenuItems.length; i++) {
          subMenuItems[i].classList.remove("selected");
        }
        menuItem.classList.add("selected");

        var pageDisplay = document.getElementById("page-display");
        pageDisplay.innerHTML = '<iframe src="' + pageURL + '"></iframe>';
      }
    }
  </script>
</head>
<body>
<div class="sidebar">
  <h1>智能简历分析系统</h1>
  <a class="nav-item" data-url="{%url 'app:about'%}" onclick="loadPage(this)">关于我们</a>
</div>
<div class="main-container">
  <div class="content-container">
    <div class="analysis-section">
      <div class="image-container">
        <img src="../../static/app/images/Add User.png" alt="单简历分析" width="100" height="100">
      </div>
      <div style="margin-top: 20px;"> <!-- Add margin-top to create space between image and button -->
        <a class="analyze-button" href="{%url 'app:single' %}">单简历分析</a>
      </div>
    </div>
    <div class="analysis-section">
      <div class="image-container">
        <img src="../../static/app/images/UUser.png" alt="多简历分析" width="100" height="100">
      </div>
      <div style="margin-top: 20px;"> <!-- Add margin-top to create space between image and button -->
        <a class="analyze-button" href="{%url 'app:multiply'%}">多简历分析</a>
      </div>
    </div>
  </div>
</div>
</body>
</html>

IRAS/app/templates/app/multi-match.html
<!DOCTYPE html>
<html>
<head>

    <style>
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            height: 100vh;
            margin: 0;
            background-color: rgba(242, 242, 242, 0);
            font-family: Arial, sans-serif;
            background-image: url("../../static/app/images/backg.jpg");
        }

        .container {
            padding: 20px;
            border: 1px solid #ddd;
            border-radius: 4px;
            background-color: #fff;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
            max-width: 500px;
            width:80%;
        }

        .property {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
        }

        h1 {
            text-align: center;
            margin-top: 0;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="property">
        <span>岗位1:文员</span>
        <span>薛菲毓</span>
    </div>
    <div class="property">
        <span>岗位2:开发工程师</span>
        <span>滕浩思</span>
    </div>
    <div class="property">
        <span>岗位3:市场营销</span>
        <span>乐巧</span>
    </div>
    <div class="property">
        <span>岗位4:产品运营</span>
        <span>王雅顺</span>
    </div>
</div>
</body>
</html>

IRAS/app/templates/app/multi-result.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>简历分析系统</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-image: url("../../static/app/images/backg.jpg");
    }


    .sidebar h1 {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
    }

    #header {
      background-color: #0d6efd; 
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 20px;
      color: #fff;
    }

    #logo {
        margin: 0;
        font-size: 24px;
        font-weight: bold;
    }

    #navigation {
      display: flex;
      align-items: center;
    }

    .nav-item, .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #1f7ddb;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .nav-item.selected, .nav-item:hover {
      background-color: #0d6efd;
      color: #fff;
    }

    #content {
      display: flex;
    }

    #sidebar {
      background-color: #0d6efd;
      width: auto;
      padding: 20px;
      height: 90vh;
    }

    #sidebar-heading {
        margin: 0;
        font-size: 24px;
        font-weight: bold;
        display: flex;
        flex-direction: column;
    }

    #sidebar-heading span {
        margin-bottom: 5px;
        color: #fff;
    }

    #main-content {
      flex: 1;
      padding: 20px;
    }

    #sub-menu {
      display: flex;
      margin-bottom: 20px;
    }

    .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #0d6efd;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .sub-menu-item.selected, .sub-menu-item:hover {
      background-color: #0751c2;
      color: #fff;
    }

    #page-display {
      border: 1px solid #ccc;
      height: 500px;
      padding: 20px;
    }

    #page-display iframe {
      width: 100%;
      height: 100%;
      border: none;
    }
  </style>
  <script>
     function loadPage(menuItem) {
      pageURL=menuItem.getAttribute("data-url");
      
      if (menuItem.classList.contains("nav-item")) {
        window.location.href = pageURL;
      }else{
        fid = menuItem.getAttribute("id")+"f";
        let frames = document.getElementsByTagName("iframe");
        for (var i=0;i<frames.length;i++){
          frames[i].setAttribute('style','display:none;');
        }
        let iframe = document.getElementById(fid);
        iframe.setAttribute('style', '');
        // let id = document.getElementById("key").getAttribute("data-id");
        let absoluteUrl = window.location.protocol + '//' + window.location.host + pageURL;
        iframe.src = absoluteUrl;
        // alert(absoluteUrl);
      }
    }
  </script>
 
</head>
<body>
<div id="header">
  <div id="logo">智能简历分析系统 > 多简历分析</div>
  <div id="navigation">
    <div class="nav-item" data-url="{%url 'app:index'%}" onclick="loadPage(this)">首页</div>
    <a class="nav-item" data-url="{%url 'app:about'%}" onclick="loadPage(this)">关于我们</a>
  </div>
</div>

<div id="content">
  <div id="main-content">
    <div id="sub-menu">
      <div id="sv" class="sub-menu-item" data-url="{%url 'app:multivis'%}" onclick="loadPage(this)">可视化</div>
      <div id="sm" class="sub-menu-item" data-url="{%url 'app:multimatch'%}" onclick="loadPage(this)">人岗匹配</div>
    </div>
    
    <div id="page-display">
      <iframe id ="svf" ></iframe>
      <iframe id ="smf" style="display: none;"></iframe>
    </div>
  </div>
</div>
</body>
</html>

IRAS/app/templates/app/multiply.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>简历分析系统</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-image: url("../../static/app/images/backg.jpg");
    }

    .sidebar {
      display: flex;
      justify-content: flex-start;
      align-items: center;
      padding: 20px;
      background-color: #0d6efd;
      color: #fff;
    }

    .sidebar h1 {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
    }

    #header {
      background-color: #0d6efd;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 20px;
      color: #fff;
    }

    #logo {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
    }

    #navigation {
      display: flex;
      align-items: center;
    }

    .nav-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #1f7ddb;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .nav-item.selected, .nav-item:hover {
      background-color: #0051ca;
      color: #fff;
    }

    #content {
      display: flex;
    }

    #sidebar {
      background-color: #0d6efd;
      width: auto;
      padding: 20px;
      height: 90vh;
    }

    #sidebar-heading {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
      display: flex;
      flex-direction: column;
    }

    #sidebar-heading span {
      margin-bottom: 5px;
      color: #fff;
    }

    #main-content {
      flex: 1;
      padding: 20px;
    }

    #sub-menu {
      display: flex;
      margin-bottom: 20px;
    }

    .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #0d6efd;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .sub-menu-item.selected, .sub-menu-item:hover {
       background-color: #0d6efd;
       color: #fff;
     }
    #page-display {
      border: 1px solid #ccc;
      height: 500px;
      padding: 20px;
    }
    #page-display iframe {
      width: 100%;
      height: 100%;
      border: none;
    }
  </style>
  <script>
    function loadPage(menuItem) {
      pageURL=menuItem.getAttribute("data-url");
      
      if (menuItem.classList.contains("nav-item")) {
        window.location.href = pageURL;
      }else{
        fid = menuItem.getAttribute("id")+"f";
        let frames = document.getElementsByTagName("iframe");
        for (var i=0;i<frames.length;i++){
          frames[i].setAttribute('style','display:none;');
        }
        let iframe = document.getElementById(fid);
        iframe.setAttribute('style', '');
        // let id = document.getElementById("key").getAttribute("data-id");
        let absoluteUrl = window.location.protocol + '//' + window.location.host + pageURL;
        iframe.src = absoluteUrl;
      }
    }
  </script>
</head>
<body>
<div id="header">
  <div id="logo">智能简历分析系统 > 多简历上传</div>
  <div id="navigation">
    <div class="nav-item" data-url="{%url 'app:index' %}"onclick="loadPage(this)">首页</div>
    <a class="nav-item" data-url="{%url 'app:about'%}" onclick="loadPage(this)">关于我们</a>
  </div>
</div>

<div id="content">

  <div id="main-content">
    <div id="sub-menu">
      <div id="po" class="sub-menu-item" data-url="{%url 'app:multiuppos' %}" onclick="loadPage(this)">岗位上传</div>
      <div id="re" class="sub-menu-item" data-url="{%url 'app:multiupres' %}" onclick="loadPage(this)">简历上传</div>
      
    </div>
    
    <div id="page-display">
      
      <iframe id ="pof" style="display: none;"></iframe>
      <iframe id ="ref" ></iframe>
    </div>
  </div>
</div>
</body>
</html>

IRAS/app/templates/app/single-result-fig.html
<!DOCTYPE html>
<html>
<head>
  <title>单简历分析</title>
  <style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      background-color: rgba(242, 242, 242, 0); /* 背景颜色透明 */
    }

    .container {
      max-width: 800px;
      text-align: center;
    }

    .image {
      max-width: 100%;
      height: auto;
    }
    .art-text {
          font-family: 'Permanent Marker', cursive;  /* 使用Permanent Marker字体 */
          font-size: 45px;
          color: #0a018d;  /* 文字颜色为红色 */
          text-shadow: 2px 2px 4px #1d1c1c;  /* 文字阴影效果 */
      }
  </style>
  <link href="https://fonts.googleapis.com/css?family=Permanent+Marker" rel="stylesheet">

</head>
<body>
<div class="container">
  {% for tag in tags %}
  <p class="art-text">{{tag}}</p>
  {%empty%}
  <p class="art-text">平平无奇的职场人一枚呀~</p>
  {%endfor%}
</div>
</body>
</html>

IRAS/app/templates/app/single-result-vis.html
<!DOCTYPE html>
<html>
<head>
  <title>单简历分析</title>
  <style>
    body {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      margin: 0;
      background-color: rgba(242, 242, 242, 0); /* 背景颜色透明 */
    }

    .container {
      max-width: 800px;
      text-align: center;
    }

    .image {
      max-width: 100%;
      height: auto;
    }
  </style>
</head>
<body>
<div class="container">
  <img class="image" src="../../static/app/images/{{name}}" alt="可视化">
</div>
</body>
</html>

IRAS/app/templates/app/single-result.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>简历分析系统</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-image: url("../../static/app/images/backg.jpg");
    }
    
    .sidebar {
      display: flex;
      justify-content: flex-start;
      align-items: center;
      padding: 20px;
      background-color: #0d6efd; 
      color: #fff;
    }

    .sidebar h1 {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
    }

    #header {
      background-color: #0d6efd; 
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 20px;
      color: #fff;
    }

    #logo {
        margin: 0;
        font-size: 24px;
        font-weight: bold;
    }

    #navigation {
      display: flex;
      align-items: center;
    }

    .nav-item, .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #0d6efd;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .nav-item.selected, .nav-item:hover {
      background-color: #0351c5;
      color: #fff;
    }

    #content {
      display: flex;
    }

    #sidebar {
      background-color: #0d6efd;
      width: auto;
      padding: 20px;
      height: 90vh;
    }

    #sidebar-heading {
        margin: 0;
        font-size: 24px;
        font-weight: bold;
        display: flex;
        flex-direction: column;
    }
    #sidebar-heading span {
        margin-bottom: 5px;
        color: #fff;
    }
    #main-content {
      flex: 1;
      padding: 20px;
    }
    #sub-menu {
      display: flex;
      margin-bottom: 20px;
    }
    .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #0d6efd;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .sub-menu-item.selected, .sub-menu-item:hover {
      background-color: #0d6efd;
      color: #fff;
    }

    #page-display {
      border: 1px solid #ccc;
      height: 500px;
      padding: 20px;
    }

    #page-display iframe {
      width: 100%;
      height: 100%;
      border: none;
    }
  </style>
  <script>
     function loadPage(menuItem) {
      pageURL=menuItem.getAttribute("data-url");
      
      if (menuItem.classList.contains("nav-item")) {
        window.location.href = pageURL;
      }else{
        fid = menuItem.getAttribute("id")+"f";
        let frames = document.getElementsByTagName("iframe");
        for (var i=0;i<frames.length;i++){
          frames[i].setAttribute('style','display:none;');
        }
        let iframe = document.getElementById(fid);
        iframe.setAttribute('style', '');
        let id = document.getElementById("key").getAttribute("data-id");
        let absoluteUrl = window.location.protocol + '//' + window.location.host + pageURL+"?id="+id;
        iframe.src = absoluteUrl;
        // alert(absoluteUrl);
      }
    }
  </script>
</head>
<body>
  <div id="key" style="display: none;" data-id = "{{id}}"></div>
<div id="header">
  <div id="logo">智能简历分析系统 > 单简历分析</div>
  <div id="navigation">
    <div class="nav-item" data-url="{%url 'app:index'%}" onclick="loadPage(this)">首页</div>
    <a class="nav-item" data-url="{%url 'app:about'%}" onclick="loadPage(this)">关于我们</a>
  </div>
</div>
<div id="content">
  <div id="main-content">
    <div id="sub-menu">
      <div class="sub-menu-item" id ="sr" data-url="{%url 'app:sr'%}" onclick="loadPage(this)">解析结果</div>
      <div class="sub-menu-item" id ="sv" data-url="{%url 'app:sv'%}" onclick="loadPage(this)">可视化</div>
      <div class="sub-menu-item" id ="sf" data-url="{%url 'app:sf'%}" onclick="loadPage(this)">人才画像</div>
    </div>
    <div id="page-display">
      <iframe id ="srf" ></iframe>
      <iframe id ="svf" style="display: none;"></iframe>
      <iframe id ="sff" src="display: none;"></iframe>
    </div>
  </div>
</div>
</body>
</html>

IRAS/app/templates/app/single.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>简历分析系统</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      font-family: Arial, sans-serif;
      background-image: url("../../static/app/images/backg.jpg");
    }

    .sidebar {
      display: flex;
      justify-content: flex-start;
      align-items: center;
      padding: 20px;
      background-color: #0d6efd; 
      color: #fff;
    }

    .sidebar h1 {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
    }

    #header {
      background-color: #0d6efd; 
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 20px;
      color: #fff;
    }

    #logo {
        margin: 0;
        font-size: 24px;
        font-weight: bold;
    }

    #navigation {
      display: flex;
      align-items: center;
    }

    .nav-item, .sub-menu-item {
      padding: 8px 16px;
      background-color: #fff;
      color: #1f7ddb;
      text-decoration: none;
      border-radius: 4px;
      font-weight: bold;
      margin-right: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .nav-item.selected, .nav-item:hover {
      background-color: #004bbc;
      color: #fff;
    }

    #content {
      display: flex;
    }

    #sidebar {
      background-color: #0d6efd;
      width: auto;
      padding: 20px;
      height: 90vh;
    }

    #sidebar-heading {
      margin: 0;
      font-size: 24px;
      font-weight: bold;
      display: flex;
      flex-direction: column;
    }

    #sidebar-heading span {
      margin-bottom: 5px;
      color: #fff;
    }

    #main-content {
      flex: 1;
      padding: 20px;
    }

    #sub-menu {
      display: flex;
      margin-bottom: 20px;
    }

    .sub-menu-item {
      margin-top: 20px;
      border: none;
      cursor: pointer;
    padding: 8px 16px;
    background-color: #0d6efd;
    color: #fff;
    text-decoration: none;
    border-radius: 4px;
    font-weight: bold;
    }

    .sub-menu-item.selected, .sub-menu-item:hover {
      background-color: #0d6efd;
      color: #fff;
    }

    #page-display {
      border: 1px solid #ccc;
      height: 80%;
      padding: 20px;
    }

    #page-display iframe {
      width: 100%;
      height: 100%;
      border: none;
    }

    /* 新增样式 */
    #custom-module {
      display: flex;
      flex-direction: column;
      align-items: center;
      background-color: transparent; /* 将背景颜色设为透明 */
      padding: 20px;
      margin-top: 10%;
      flex: 1;
    }

    #custom-module .input-container {
      display: flex;
      align-items: center;
      margin-bottom: 10px;
    }

    #custom-module .input-container input[type="text"] {
      width: 80%;
      padding: 10px;
      margin-right: 10px;
    }

    #custom-module .button-container {
      display: flex;
      justify-content: flex-start;
      width: 100%;
      margin-bottom: 10px;
    }

    #custom-module .button-container button {
      margin-right: 10px;
    }

    #custom-module textarea {
      width: 100%;
      height: 200px;
      padding: 10px;
      resize: vertical;
      overflow: auto;
      margin-bottom: 10px;
    }

    #custom-module button {
    margin-top: 0px;
    border: none;
    cursor: pointer;
    padding: 6px 22px;
    background-color: #0d6efd;
    color: #fff;
    text-decoration: none;
    border-radius: 15px;
    font-weight: bold;
}

    #start-analysis-button {
      margin-top: 20px;
      border: none;
      cursor: pointer;
    padding: 8px 16px;
    background-color: #0d6efd;
    color: #fff;
    text-decoration: none;
    border-radius: 4px;
    font-weight: bold;
    }
    .button-effect {
      transform: scale(0.95);
      transition: transform 0.2s;
    }

    .button-effect:active {
      transform: scale(1);
    }
  </style>
  <script>
    function handleFileSelect(evt) {
      evt.preventDefault();
      var files = evt.dataTransfer.files;
      if (files.length > 0) {
        var file = files[0];
        document.getElementById('file-input').value = file.name;
      }
    }
    function handleFileInput(evt) {
      evt.preventDefault();
      var files = evt.target.files;
      if (files.length > 0) {
        var file = files[0];
        document.getElementById('file-input').value = file.name;
      }
    }
    function loadPage(menuItem) {
      pageURL=menuItem.getAttribute("data-url");
      
      if (menuItem.classList.contains("nav-item")) {
        window.location.href = pageURL;
      }else{
        var iframe = document.getElementById('ifr');
        iframe.setAttribute('style', '');
        var absoluteUrl = window.location.protocol + '//' + window.location.host + pageURL;
        iframe.src = absoluteUrl;
      }
    }
  </script>
  <script>
    window.addEventListener('DOMContentLoaded', (event) => {
      const buttons = document.querySelectorAll('#select-button, #start-analysis-button');

      buttons.forEach((button) => {
        button.addEventListener('mouseover', () => {
          button.classList.add('button-effect');
        });

        button.addEventListener('mouseout', () => {
          button.classList.remove('button-effect');
        });

        button.addEventListener('click', () => {
          button.classList.add('button-effect');
          // 在这里可以添加按钮点击后的其他操作
        });
      });
    });
  </script>

</head>
<body>
<div id="header">
  <div id="logo">智能简历分析系统 > 单简历上传</div>
  <div id="navigation">
    <div class="nav-item" data-url = "{%url 'app:index' %}"onclick='loadPage(this)'>首页</div>
    <a class="nav-item" data-url="{%url 'app:about'%}" onclick="loadPage(this)">关于我们</a>
  </div>
</div>

<div id="content">
  <div id="main-content">
    <div id="custom-module">
        <form id="fr"action="{%url 'app:singleupload'%}" method="post"enctype="multipart/form-data" >
          {% csrf_token %}
          <div class="input-container">
          <input name="file" type="file" id="file-picker" style="display:none;" onchange="handleFileInput(event)">
          <input name="title"type="text" id="file-input" placeholder="选择文件或手动输入文件地址" ondrop="handleFileSelect(event)" ondragover="event.preventDefault()">
          <button type="button" id="select-button" onclick="document.getElementById('file-picker').click()">选择文件</button><br>
        </div>
      <textarea name="text" placeholder="请输入文本..."></textarea>
      <button id="start-analysis-button" type="submit">开始分析</button>
    </form>
    </div>
  </div>
</div>
</body>